name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run integration tests
        env:
          HUNTER_API_KEY: ${{ secrets.HUNTER_API_KEY }}
        run: |
          # Run integration tests with pytest
          pytest tests/integration/ -v --tb=short

      - name: Run integration tests with coverage
        env:
          HUNTER_API_KEY: ${{ secrets.HUNTER_API_KEY }}
        run: |
          # Run integration tests with coverage report
          pytest tests/integration/ --cov=hunter_wrapper --cov-report=term-missing --cov-report=xml

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
