name: Pre-commit Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    name: Run Pre-commit Hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pre-commit environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install main dependencies for proper import resolution
          pip install -r requirements.txt
          # Install dev dependencies including pre-commit
          pip install -r requirements-dev.txt

      - name: Run pre-commit hooks
        run: |
          # Run all pre-commit hooks on all files
          pre-commit run --all-files --show-diff-on-failure --color=always

      - name: Check for hook failures
        if: failure()
        run: |
          echo "❌ Pre-commit checks failed!"
          echo "Please run 'pre-commit run --all-files' locally and commit the fixes."
          echo ""
          echo "To set up pre-commit locally:"
          echo "  1. Install dev dependencies: pip install -r requirements-dev.txt"
          echo "  2. Install pre-commit hooks: pre-commit install"
          echo "  3. Run manually: pre-commit run --all-files"
          exit 1
